// 与 server/src/actions.js 中的 build(params) 一一对应的表单字段描述。
export const ACTION_FIELDS = {
  "ingest.discover": [
    { name: "url", label: "起始 URL", type: "text", placeholder: "https://example.com", required: true },
    { name: "depth", label: "发现深度（跟随分支链接层数）", type: "number", default: 1 },
    { name: "maxPages", label: "最多发现页面数（安全上限）", type: "number", default: 100 },
    { name: "allowCrossDomain", label: "允许跨域跟随", type: "checkbox" },
    { name: "ignoreRobots", label: "忽略 robots.txt", type: "checkbox" },
  ],
  "ingest.crawl": [
    { name: "output", label: "输出目录（仓库内相对路径，原始文档）", type: "text", placeholder: "ObsidianRag/_crawled", required: true },
    { name: "urls", label: "确认抓取的 URL（每行一个）", type: "textarea", placeholder: "https://example.com/a\nhttps://example.com/b" },
    { name: "depth", label: "抓取深度（一般填 0，分支已由 discover 确认）", type: "number", default: 0 },
    { name: "ignoreRobots", label: "忽略 robots.txt", type: "checkbox" },
    { name: "overwrite", label: "覆盖已存在文件", type: "checkbox" },
  ],
  "ingest.run": [
    { name: "source", label: "源目录", type: "text", placeholder: "ObsidianRag", required: true },
    { name: "output", label: "输出目录", type: "text", placeholder: "ObsidianRag_md", required: true },
    { name: "overwrite", label: "覆盖已存在文件", type: "checkbox" },
    { name: "noPdfPages", label: "跳过 PDF 分页", type: "checkbox" },
    { name: "noHtmlClean", label: "关闭 HTML 去噪", type: "checkbox" },
    { name: "noInjectionScan", label: "关闭 Prompt 注入检测", type: "checkbox" },
    { name: "noQualityFilter", label: "关闭质量过滤", type: "checkbox" },
    { name: "noDedup", label: "关闭近似去重", type: "checkbox" },
  ],
  "ingest.status": [
    { name: "source", label: "源目录", type: "text", required: true },
    { name: "output", label: "输出目录", type: "text", required: true },
  ],
  "ingest.clean": [
    { name: "source", label: "源目录", type: "text", required: true },
    { name: "output", label: "输出目录", type: "text", required: true },
  ],
  "ingest.distill": [
    { name: "source", label: "md 源目录（本地目录，需为清洗后的 md）", type: "text", required: true },
    { name: "output", label: "Obsidian 知识库输出目录", type: "text", required: true },
    { name: "profile", label: "蒸馏 profile", type: "select", options: ["", "concept", "algorithm"] },
    { name: "role", label: "外部 AI 角色（role）", type: "select", options: ["", "teacher", "fallback", "runner"] },
    { name: "model", label: "覆盖模型（可选，形如 provider:model）", type: "text", placeholder: "deepseek:deepseek-chat" },
    { name: "overwrite", label: "覆盖已存在文件", type: "checkbox" },
    { name: "noLink", label: "跳过关联链接", type: "checkbox" },
  ],
  "ingest.distillLink": [{ name: "output", label: "知识库(vault)根目录", type: "text", required: true }],
  "provider.list": [],
  "provider.ask": [
    { name: "prompt", label: "Prompt", type: "textarea", required: true },
    {
      name: "provider",
      label: "provider",
      type: "select",
      options: ["", "openai", "deepseek", "anthropic", "gemini", "ollama", "claude_code", "codex"],
    },
    { name: "role", label: "role", type: "select", options: ["", "teacher", "fallback", "runner"] },
  ],
  "pipeline.datagen": [
    { name: "corpus", label: "语料目录（ModelIngest 产物）", type: "text", required: true },
    { name: "out", label: "输出 jsonl 路径", type: "text", placeholder: "pipeline/out/train.jsonl", required: true },
    { name: "limit", label: "限制文件数（试运行，可选）", type: "number" },
    { name: "perChunk", label: "每块样本数（默认 3）", type: "number" },
    { name: "role", label: "role", type: "select", options: ["", "teacher", "fallback", "runner"] },
  ],
  "pipeline.train": [
    { name: "config", label: "训练配置文件", type: "text", required: true },
    { name: "execute", label: "确认真正执行训练（否则仅 dry-run 打印命令）", type: "checkbox" },
  ],
  "pipeline.serve": [
    { name: "gguf", label: "GGUF 模型路径", type: "text", required: true },
    { name: "name", label: "Ollama 模型名（默认 modeltoolbox-private）", type: "text" },
    { name: "mmproj", label: "mmproj 路径（可选，视觉模型需要）", type: "text" },
    { name: "execute", label: "确认真正执行（否则仅 dry-run 打印命令）", type: "checkbox" },
  ],
  "memory.status": [],
  "memory.repos": [],
  "memory.build": [],
  "memory.detectChanges": [{ name: "base", label: "对比基线（可选，如 main）", type: "text" }],
};
